name = "fp-lean"
version = "0.1.0"
defaultTargets = ["fp-lean"]
moreLeanArgs = ["--tstack=4096"]
moreGlobalServerArgs = ["--tstack=4096"]

[[lean_lib]]
name = "Fp"

[[lean_lib]]
name = "Fp.Theorems"

[[lean_exe]]
name = "fp-lean"
root = "Main"
