name = "fp-lean"
version = "0.1.0"
defaultTargets = ["fp-lean"]
moreLeanArgs = ["--tstack=1024"]
moreGlobalServerArgs = ["--tstack=1024"]

[[lean_lib]]
name = "Fp"

[[lean_exe]]
name = "fp-lean"
root = "Main"
